<?php

$plugin = array(
    'title' => t('Few Rows'),
    'category' => t('Oyster'),
    'icon' => 'fewrows.png',
    'theme' => 'fewrows',
    'admin css' => 'fewrows.css',
    'regions' => array(
        'top_content' => t('Top Content'),
        'left_content' => t('Left Content'),
        'right_content' => t('Right Content'),
        'col_1' => t('Column 1'),
        'col_2' => t('Column 2'),
        'col_3' => t('Column 3'),
        'col_4' => t('Column 4'),
        'middle_content' => t('Middle Content'),
        'bot_col_1' => t('Bottom Column 1'),
        'bot_col_2' => t('Bottom Column 2'),
        'bot_col_3' => t('Bottom Column 3'),
        'bottom_content' => t('Bottom Content'),
        'logos_content' => t('Logos Content'),
        'col_11' => t('Publication Column 1'),
        'col_21' => t('Publication Column 1'),
        'col_31' => t('Publication Column 1')
    ),
);
